site: Kézdi Gábor

url: https://kezdigabor.life
baseurl: 

collections:
  pages:
    output: true
    permalink: /:name
  topics:
    output: true
    permalink: /topic/:name
  tributes:
    output: true
    permalink: /tribute/:name

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "topics"
    values:
      layout: "topic"
  -
    scope:
      path: ""
      type: "tributes"
    values:
      layout: "tribute"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 6
paginate_path: "/blog/page:num/"
  